### ISSUE TITLE
After type-strings array is finished hide the cursor

### ISSUE THREAD

**Issue by psmod2** [codekraft-studio/angular-typed#6]
Hello,

I have the following snippet:

```
<span start-timeout="10" type-speed="50" back-speed="40" html-mode="" typed=""
type-strings="[
            'a^2000',
            'b^2000',
            'c^2000' "]>
</span>
```

However once it is over - how do i hide the cursor, or at least have it flashing? it's currently just showing as a solid | which looks very much like the letter l

Also what exactly does the `html-mode: Enable the html parse mode` mean?

Thanks

**Comment by b4dnewz** [comment]
hi @psmod2 

> Also what exactly does the html-mode: Enable the html parse mode mean?

It means you can write HTML inside your type-strings and it will be rendered as HTML, for example as in the [demo](https://github.com/codekraft-studio/angular-typed/blob/master/index.html#L29) code: `type-strings="it supports <code>html markup</code>^750 and timings^500"`

> However once it is over - how do i hide the cursor, or at least have it flashing?

For the blink effect you have to do it yourself, but there is an [example](https://github.com/codekraft-studio/angular-typed/blob/master/src/angular-typed.css) in the project, you can grab that and add it your css file or write a new one, be sure to use **typed-cursor** class selector.

```css
.typed-cursor {
  animation: blink-animation 850ms steps(5, start) infinite;
  -webkit-animation: blink-animation 850ms steps(5, start) infinite;
  margin-left: 2px;
}

@keyframes blink-animation {
  to {
    visibility: hidden;
  }
}

@-webkit-keyframes blink-animation {
  to {
    visibility: hidden;
  }
}
```

In order to hiding it once the typing has done I need to add more options to the component.
